#!/usr/bin/env ruby

success = true
begin
  log_options = { out: 'bootstrap-rails.log', err: %i[child out] }
  foreman_pids = [
    spawn('./run', 'db', log_options),
    spawn('./run', 'gitaly', log_options)
  ]

  [
    %w[support/wait-postgresql-ready support/exec-cd gitlab bundle exec rake db:create],
    %w[support/exec-cd gitlab bundle exec rake dev:setup]
  ].each do |cmd|
    success &&= system({ 'force' => 'yes', 'BOOTSTRAP' => '1' }, *cmd)
  end
ensure
  foreman_pids.each { |pid| Process.kill('TERM', pid) }
end

foreman_pids.each { |pid| Process.wait(pid) }

exit true if success

abort "#{$PROGRAM_NAME} failed"
