#!/usr/bin/env ruby
require 'socket'

HOST = '127.0.0.1'
DATABASE = 'gitlab'

def wait_for_socket(host,port)
  30.times do
    begin
      TCPSocket.new(host, port)
      return true
    rescue Errno::ECONNREFUSED
      sleep 1
    end
  end
  false
end

def main(host, port)
  foreman_pid = spawn('./run', 'db')

  abort "#$0: could not connect to InfluxDB at #{host}:#{port}" unless wait_for_socket(host, port)

  IO.popen(%W(influxdb/bin/influx -host #{host} -port #{port}), 'w') do |influx|
    influx.puts "CREATE DATABASE #{DATABASE} WITH duration 1d REPLICATION 1;"
  end
  if !$?.success?
    abort "#$0: failed to create InfluxDB database #{DATABASE}"
  end

  env = {
    'INFLUX_HOST' => "#{host}",
    'INFLUX_PORT' => "#{port}",
    'INFLUX_USER' => "",
    'INFLUX_PASSWORD' => "",
    'INFLUX_DATABASE' => "#{DATABASE}",
  }
  if !system(env, *%W(bundle exec rake), chdir: 'influxdb/influxdb-management')
    abort "#$0: failed to run influxdb-managemant Rake script"
  end
ensure
  Process.kill('TERM', foreman_pid)
  Process.waitpid(foreman_pid)
end

if ARGV.count != 1
  abort "Usage: #$0 INFLUXDB_HTTP_PORT"
end

port = ARGV.shift

main(HOST, port)
