#!/usr/bin/env ruby
require 'socket'
require 'net/http'

def main
  host = '127.0.0.1'
  port = '9999'

  db_pid = spawn('./run', 'db')
  grafana_pid = spawn('./run', 'grafana')

  abort "#$0: could not connect to Grafana at #{host}:#{port}" unless wait_socket(host, port)

  http = Net::HTTP.new(host, port)
  request = Net::HTTP::Post.new('/api/datasources')
  request.basic_auth('admin', 'admin')
  request.add_field('Content-Type', 'application/json')
  request.body = <<EOS
{
    "name": "InfluxDB",
    "type": "influxdb",
    "url": "http://localhost:8086",
    "access": "direct",
    "database": "gitlab",
    "isDefault": true
}
EOS
  puts http.request(request).body
ensure
  [grafana_pid, db_pid].each do |pid|
    Process.kill('TERM', pid)
    Process.wait(pid)
  end
end

def wait_socket(host, port)
  30.times do
    begin
      TCPSocket.new(host, port)
      return true
    rescue Errno::ECONNREFUSED
      sleep 1
    end
  end
  false
end

if !ARGV.empty?
  abort "Usage: #$0"
end

main