#!/usr/bin/env ruby
require 'socket'

HOST = '127.0.0.1'.freeze
DATABASE = 'gitlab'.freeze

def wait_for_socket(host, port)
  30.times do
    begin
      TCPSocket.new(host, port)
      return true
    rescue Errno::ECONNREFUSED
      sleep 1
    end
  end
  false
end

def main(host, port)
  system(*%w[gdk start influxdb])

  abort "#{$PROGRAM_NAME}: could not connect to InfluxDB at #{host}:#{port}" unless wait_for_socket(host, port)

  IO.popen(%W[influxdb/bin/influx -host #{host} -port #{port}], 'w') do |influx|
    influx.puts "CREATE DATABASE #{DATABASE} WITH duration 1d REPLICATION 1;"
  end

  abort "#{$PROGRAM_NAME}: failed to create InfluxDB database #{DATABASE}" unless $?.success?

  env = {
    'INFLUX_HOST' => host.to_s,
    'INFLUX_PORT' => port.to_s,
    'INFLUX_USER' => "",
    'INFLUX_PASSWORD' => "",
    'INFLUX_DATABASE' => DATABASE.to_s
  }
  unless system(env, *%w[bundle exec rake], chdir: 'influxdb/influxdb-management')
    abort "#{$PROGRAM_NAME}: failed to run influxdb-managemant Rake script"
  end
end

abort "Usage: #{$PROGRAM_NAME} INFLUXDB_HTTP_PORT" if ARGV.count != 1

port = ARGV.shift

main(HOST, port)
