#!/usr/bin/env ruby

success = true
begin
  foreman_pids = [
    spawn('./run', 'db'),
    spawn('./run', 'gitaly')
  ]

  [
    %w[bundle exec rake db:create],
    %w[bundle exec rake dev:setup]
  ].each do |cmd|
    success &&= system({ 'force' => 'yes', 'BOOTSTRAP' => '1' }, *cmd, chdir: 'gitlab')
  end
ensure
  foreman_pids.each { |pid| Process.kill('TERM', pid) }
end

foreman_pids.each { |pid| Process.wait(pid) }

exit true if success

abort "#{$PROGRAM_NAME} failed"
