#!/usr/bin/env ruby

begin
  foreman_pid = spawn('./run', 'db')
  [
    %W(bundle exec rake db:create),
    %W(bundle exec rake dev:setup),
  ].each do |cmd|
    system({'force' => 'yes', 'BOOTSTRAP' => '1'}, *cmd, chdir: 'gitlab')
  end
ensure
  Process.kill('TERM', foreman_pid)
end
