#!/usr/bin/env ruby

success = true
begin
  system(*%w[gdk start postgresql-geo])

  [
    %w[bundle exec rake geo:db:create],
    %w[bundle exec rake geo:db:setup],
  ].each do |cmd|
    success &&= system({ 'force' => 'yes', 'BOOTSTRAP' => '1' }, *cmd, chdir: 'gitlab')
  end

  [
    %w[make postgresql/geo-fdw]
  ].each do |cmd|
    success &&= system({ 'force' => 'yes', 'BOOTSTRAP' => '1' }, *cmd)
  end
end

exit true if success

abort "#{$PROGRAM_NAME} failed"
