#!/bin/sh
postgres_dir=$(gdk config get postgresql.dir 2>/dev/null)
pg_port=$(gdk config get postgresql.port 2>/dev/null)

for db in gitlabhq_development gitlabhq_test; do
  cat <<EOF
\connect ${db}
CREATE EXTENSION pg_trgm;
EOF
done | psql -h "$(postgres_dir)" -d template1 -p "$pg_port"
