#!/usr/bin/env ruby
#
# This script implements 'cd foo && exec bar' without the need to invoke
# /bin/sh for the ' && '.

abort "Usage: #{$0} DIRECTORY COMMAND [ARGUMENTS ...]" if ARGV.count < 2

Dir.chdir(ARGV.shift)
exec(*ARGV)
