#!/usr/bin/env ruby

def run(commands)
  IO.popen(commands, err: '/dev/null', &:read).chomp
rescue Errno::ENOENT
  ''
end

brew_cellar_pg96 = run(%w[brew --cellar postgresql@9.6])

unless brew_cellar_pg96.empty?
  brew_cellar_pg96_bin = Dir.glob(File.join(brew_cellar_pg96, '/*/bin'))

  if brew_cellar_pg96_bin.any?
    puts brew_cellar_pg96_bin.last
    exit
  end
end

system(*%w[pg_config --bindir])
