#!/bin/bash
replication_include="include 'replication.conf'"
postgres_dir="$( cd "$1" && pwd )"
if ! grep -Fxq "$replication_include" $postgres_dir/data/postgresql.conf; then
  echo $replication_include >> $postgres_dir/data/postgresql.conf
fi

if [ ! -f "$postgres_dir/data/replication.conf" ]; then
  cat <<EOF > $postgres_dir/data/replication.conf
wal_level = hot_standby
max_replication_slots = 1
max_wal_senders = 10
wal_keep_segments = 10
hot_standby = on
EOF
fi
