#!/usr/bin/env ruby
#
# Translate SIGTERM to SIGINT to request a 'fast shutdown' from Postgres.

Signal.trap('TERM') do
  puts "Sending INT to #{$pid}"
  Process.kill('INT', $pid)
end

$pid = spawn(*ARGV)
Process.wait($pid)
exit $?.exitstatus
