#!/bin/bash
gitlab_include="include 'gitlab.conf'"
postgres_dir="$( cd "$1" && pwd )"

if ! grep -Fxq "$gitlab_include" $postgres_dir/data/postgresql.conf; then
  echo $gitlab_include >> $postgres_dir/data/postgresql.conf
fi

if [ ! -f "$postgres_dir/data/gitlab.conf" ]; then
  cat <<EOF > $postgres_dir/data/gitlab.conf
random_page_cost = '1'
work_mem = '16MB'
maintenance_work_mem = '64MB'
shared_buffers = '256MB'
EOF
fi
