#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Must provide a filename as an argument"
    exit 1
fi

file=$1

if [ ! -f "$file" ]; then
    exit 0
fi

size=$(wc -c < "$file")

if [ "$size" -eq 0 ]; then
  echo "Removing empty $file"
  rm "$file"
fi
