#!/usr/bin/env ruby

def run(cmd)
  puts cmd.join(' ')
  system(*cmd)
end

ci_project_dir = ENV['CI_PROJECT_DIR']
ci_sha = ENV['CI_COMMIT_SHA']

# We need to retrieve the commit SHA if the source project is a fork
if ci_project_dir && ci_sha
  run(%W[git remote add source #{ci_project_dir}])
  run(%W[git fetch source #{ci_sha}])
end

if ci_sha
  run(%w[git merge --ff-only origin/master])
else
  run(%W[git checkout #{ci_sha}])
end
