#!/bin/sh
set -e # exit on uncaught failure
gitlab_base_url="https://gitlab.com"
gitlab="gitlab"
gitlab_org="gitlab-org"
remote_name="upstream"

cd ./gitlab

git_remote_add_upstream() {
  echo "Remote origin is ${1}, adding remote ${remote_name} to ${1}"
  git remote add "${remote_name}" "${gitlab_base_url}/${gitlab_org}/${1}.git"
}

grep_git_remote() {
  git remote -v | grep -q "${1}\.git.*$"
}

if git remote | grep -q "^${remote_name}$"; then
  echo "Remote ${remote_name} already exists in $(pwd). Exiting."
  exit 0
fi

# Try to determine if remote should be ee or ce

git_remote_add_upstream ${gitlab}

git remote set-url --push "${remote_name}" none # make 'upstream' fetch-only
echo "Fetching master from ${remote_name}..."
git fetch "${remote_name}" master

# check if the 'master' branch already exists
if git show-ref --verify --quiet refs/heads/master; then
  git branch --set-upstream-to="${remote_name}/master" master
else
  git branch master "${remote_name}/master"
fi
