#!/usr/bin/env ruby
PG_HOST = "#{Dir.pwd}/postgresql".freeze
PG_PORT_FILE = File.join(Dir.pwd, 'postgresql_port')
PG_PORT = File.exist?(PG_PORT_FILE) ? File.read(PG_PORT_FILE) : 5432

def main
  abort "#{$PROGRAM_NAME}: could not connect to Postgres at #{PG_HOST}" unless pg_ready?

  exec(*ARGV)
end

def pg_ready?
  10.times do
    if system(*%W[psql -h #{PG_HOST} -d template1 -p #{PG_PORT} -c SELECT\ now()], out: '/dev/null', err: '/dev/null')
      return true
    end
    sleep 1
  end
  false
end

abort "Usage: #{$PROGRAM_NAME} COMMAND [ARGUMENT...]" if ARGV.empty?

main
