#!/bin/sh
gdk_path=$(pwd)/gdk

printf "Creating executable: ${gdk_path} ... "

cat > ${gdk_path} <<EOF
#!/bin/sh
export GDK_ROOT=$(pwd)
export GDK_INVOKED=\$0
exec /usr/bin/env ruby \$GDK_ROOT/gdk.rb "\$@"
EOF

chmod +x ${gdk_path}
echo done
echo
./gdk help
