#!/bin/sh

# TODO rewrite config parsing in lib/run.rb

main() {
  # Try to read the gitlab-workhorse host:port from the environments
  if [ "x${host}" = x ]; then
    # Try a host/hostname file
    host="$(cat host 2>/dev/null || cat hostname 2>/dev/null)"
  fi
  if [ "x${port}" = x ]; then
    # Try a port file
    port="$(cat port 2>/dev/null)"
  fi
  if [ "x${relative_url_root}" = x ]; then
    # Try a relative_url_root file
    relative_url_root="$(cat relative_url_root 2>/dev/null)"
  fi

  # Fall back to localhost:3000
  host="${host:-localhost}"
  port="${port:-3000}"
  relative_url_root="${relative_url_root:-/}"

  export host
  export port
  export relative_url_root

  exec ruby lib/run.rb "$@"
}

if [ "x$GDK_RUNIT" = "x1" ]; then
  echo "$0 is disabled while using runit"
  exit 1
fi

main "$@"
