#!/bin/sh

# Try to read the gitlab-workhorse port from the environment
if [ x$port = x ] ; then
  # Try a port file
  port=$(cat port 2>/dev/null)
fi

# Fall back to 3000
port=${port:-3000}

print_port() {
  echo "Starting GitLab in $(pwd) on port ${port}"
  echo
  echo
}

foreman_start() {
 exec env port=${port} foreman start "$@"
}

db() {
  foreman_start -c all=0,redis=1,postgresql=1,openldap=1,influxdb=1
}

app() {
  print_port
  foreman_start -c all=0,rails-web=1,rails-background-jobs=1,gitlab-workhorse=1,workhorse-stunnel=1,grafana=1
}

grafana() {
  foreman_start -c all=0,grafana=1
}

all() {
  print_port
  foreman_start
}

case x$1 in
xdb)
  db
  ;;
xapp)
  app
  ;;
xgrafana)
  grafana
  ;;
x*)
  all
  ;;
esac
