#!/bin/sh

# Spellcheck rule definitions
#
# https://github.com/koalaman/shellcheck/wiki/SC1071 - ShellCheck only supports sh/bash/dash/ksh scripts. Sorry!

root="$(realpath "$(dirname "${0}")/../..")"

exec find "${root}/bin" "${root}/support" "${root}/support/ci" "${root}/support/completions" \
      -maxdepth 1 \
      -type f \
      -not -path "*/support/pg_hba.conf.add" \
      -not -path "*/support/.rubocop.yml" \
      -not -path "*.swp" \
      -print0 \
| xargs -0 shellcheck --exclude=SC1071 --external-sources --
