#!/bin/bash -e

parent_path=$(dirname $0)

source ${parent_path}/functions

init
checkout ${CI_COMMIT_SHA}
install
run &
echo "> Waiting 90 secs to give GDK a chance to boot up.."
sleep 90
${parent_path}/test_url
