#!/bin/bash -e

source support/ci/functions

init
checkout "master"
install
run &
echo "> Waiting 45 secs to give GDK a change to boot up.."
sleep 45
checkout ${CI_COMMIT_SHA}
update
echo "> Waiting 60 secs to give GDK a change to boot up.."
sleep 60
test_url
