#!/bin/bash -e

source support/ci/functions

init
checkout "master"
install
run &
echo "> Waiting 90 secs to give GDK a change to boot up.."
sleep 90
checkout ${CI_COMMIT_SHA}
update
echo "> Waiting 90 secs to give GDK a change to boot up.."
sleep 90
test_url
