#!/bin/bash -ex

parent_path=$(dirname $0)

source ${parent_path}/functions.sh

init
checkout "master"
install
run &
echo "> Waiting 90 secs to give GDK a chance to boot up.."
sleep 90
checkout ${CI_COMMIT_SHA}
update
echo "> Waiting 90 secs to give GDK a chance to boot up.."
sleep 90
${parent_path}/test_url
