#!/bin/bash -ex

parent_path=$(dirname "$0")

# shellcheck source=support/ci/functions.sh
source "${parent_path}"/functions.sh

init
checkout "${CI_COMMIT_SHA}"
install
start
wait_for_boot
"${parent_path}"/test_url
