#!/bin/bash -ex

parent_path=$(dirname $0)

source ${parent_path}/functions.sh

init

# test GDK install
checkout "master"
install
start
echo "> Waiting 90 secs to give GDK a chance to boot up.."
sleep 90
${parent_path}/test_url

# test GDK self-update
checkout ${CI_COMMIT_SHA}
restart
echo "> Waiting 90 secs to give GDK a chance to boot up.."
sleep 90
${parent_path}/test_url

# test GDK components update
update
echo "> Waiting 90 secs to give GDK a chance to boot up.."
sleep 90
${parent_path}/test_url
